### ISSUE TITLE
Capitalization problems

### ISSUE THREAD

**Issue by satieairame** [katelyntoigo/issues-lab#6]
https://github.com/katelyntoigo/issues-lab/blob/1f61dcf8b6b424eb8f84a7bf6c2c6c1a29a0908b/got_issues.Rmd#L34

Hi! There are several capital letters that should be lowercase here: (x = "StorM CategorRY",

"storm category"

**Comment by katelyntoigo** [comment]
I didn't even notice this!  Thanks for picking up on it.  It has been fixed!
